### PR TITLE
update xref property type with new names

### PR DESCRIPTION
**Pull request by ahmadshadab**
See https://www.ebi.ac.uk/panda/jira/browse/TRM-27012 for details.

### CODE REVIEW

**Comment by jieluo321** [comment]
Looks good to me. 
I created drlineconfiguration.json file.  xml tags changed for some of the cross references. Or some new cross references may not configure it properly.  In the production pipeline xml project, there is a file called drlineconfiguration.xml. This file has been properly updated. We need some kind of mechanism to synchronise these two file

**Comment by jieluo321** [comment]
Also we need a test case  for each cross reference to check and test json and xml tags.

**Comment by ahmadshadab** [comment]
> Also we need a test case for each cross reference to check and test json and xml tags. Or add test for org.uniprot.core.xml.uniprot.UniProtCrossReferenceConverter to cover all the cross references and new cross references

Hi @jieluo321 ,
I have added test cases for new/problematic cross references reported by Jerven. UniProtKBCrossReferenceConverterTest is test class for org.uniprot.core.xml.uniprot.UniProtCrossReferenceConverter. Do you want me to add property value test cases for other cross references as well? They will be 70-80 of xrefs.

**Comment by ahmadshadab** [comment]
> 

Hi @jieluo321 ,
Could you please share the link of Production pipeline xml project repository?

**Pull request merged**
