### PR TITLE
new core-domain-utils module to store client utility methods

### PR DESCRIPTION
**Pull request by eddturner**
currently only containing util method to extract GOTerms from a UniProtKBEntry, but in future can contain any number of helpers.

This helper has been requested by AA.

### CODE REVIEW

**Comment by uniprot** [comment]
UniProtKBEntryUtilsTest fails because CVSystemProperties.getGOLocation returns nothing.

**Comment by uniprot** [comment]
with core-domain-utils module, in the future, we can re-arrange some classes, some of them may belong to core-domain-util. We don't need to do it now. When we have time, we can do something about it

**Comment by uniprot** [comment]
About CVSystemProperties, this class was added a while ago. It does not cover all CV files. We could extend to add more function to cover other CV files such as keyword subcellularlocation. 
What should happen if System properties are not defined? do we have a default location such as ftp location?

**Comment by uniprot** [comment]
When test is passed, it is ok. We can create some jiras for future development

**Comment by eddturner** [comment]
> UniProtKBEntryUtilsTest fails because CVSystemProperties.getGOLocation returns nothing.
If you run by maven, maven will set this system property so that it does pass.

```xml
<!-- POM snippet -->
<property>
    <name>cv.go.location</name>
    <value>${project.build.directory}/../src/test/resources/uniprotkb/go</value>
</property>
```

**Comment by eddturner** [comment]
> When test is passed, it is ok. We can create some jiras for future development

I agree we can add more functionality for future, but for now it is mainly a placeholder.

**Pull request merged**
