### PR TITLE
New proteome xsd code changes

### PR DESCRIPTION
**Pull request by LeonardoGonzales**

### CODE REVIEW

**Comment by jieluo321** [comment]
BuscoReport, we may soon add lineageDBcreatedDate
CPDReport, we may change CPD report as well in the near future

**Comment by jieluo321** [comment]
i updated proteome_example.xml test data. I think that it will be better to have some roundtrip tests for proteome xml parser

**Comment by jieluo321** [comment]
I think that for now proteome domain is good. It is likely that we will need to change proteome and proteome domain in the near future, but not before new website release

**Review by jieluo321 — APPROVED** [review]

**Review by jieluo321 — APPROVED** [review]

**Comment by uniprot** [comment]
It is fine

**Pull request merged**
