### PR TITLE
Refactoring core domain

### PR DESCRIPTION
**Pull request by rizwan-ishtiaq**

### CODE REVIEW

**Comment by jluo321** [comment]
the keyword KeywordEntryKeyword is so strange. Why not just call Keyword or KeywordId
If it calls Keyword, in UniProtEntry, we can call UniProtKeyword something like that

**Comment by jluo321** [comment]
Also KeywordGeneOntology, Can you create GoTerm also as cv? Indexer and store will need this as well

**Comment by jluo321** [comment]
crossref is also cv and can be merged with xdb

**Comment by jluo321** [comment]
from SubcellularLocationEntry extracting getId and getAccession(), create SubcellularLocationId
interface having getId and getName(), Id will be the accession in file and name will be the id in the file, then you can refactor SubcellularLocationValue, this will be extend SubcellularLocationId and HasEvidences

**Comment by rizwan-ishtiaq** [comment]
jie, 1st 3 comments are done now
i will do subcell in next PR

**Pull request merged**
